#if !canImport(ObjectiveC)
import XCTest

extension PitchSpellingCategoryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PitchSpellingCategoryTests = [
        ("testLetterNamePredecessor", testLetterNamePredecessor),
        ("testLetterNameSuccessor", testLetterNameSuccessor),
        ("testNeutralLetterName", testNeutralLetterName),
        ("testPCEight_AFlat", testPCEight_AFlat),
        ("testPCEightNeutral_Nil", testPCEightNeutral_Nil),
        ("testPCEightUp_GSharp", testPCEightUp_GSharp),
        ("testPCFourDown_FFlat", testPCFourDown_FFlat),
        ("testPCFourNeutral_ENatural", testPCFourNeutral_ENatural),
        ("testPCFourUp_DDoubleSharp", testPCFourUp_DDoubleSharp),
        ("testPCOneDown_DFlat", testPCOneDown_DFlat),
        ("testPCOneNeutral_CSharp", testPCOneNeutral_CSharp),
        ("testPCOneUp_BDoubleSharp", testPCOneUp_BDoubleSharp),
        ("testPCThreeDown_FDoubleFlat", testPCThreeDown_FDoubleFlat),
        ("testPCThreeNeutral_EFlat", testPCThreeNeutral_EFlat),
        ("testPCThreeUp_DSharp", testPCThreeUp_DSharp),
        ("testPCTwoDown_EDoubleFlat", testPCTwoDown_EDoubleFlat),
        ("testPCTwoNeutral_DNatural", testPCTwoNeutral_DNatural),
        ("testPCTwoUp_CDoubleSharp", testPCTwoUp_CDoubleSharp),
        ("testPCZeroDown_DDoubleFlat", testPCZeroDown_DDoubleFlat),
        ("testPCZeroNeutral_CNatural", testPCZeroNeutral_CNatural),
        ("testPCZeroUp_BSharp", testPCZeroUp_BSharp),
    ]
}

extension TendencyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TendencyTests = [
        ("testPitchSpellingFromTendenciesBSharp", testPitchSpellingFromTendenciesBSharp),
        ("testPitchSpellingFromTendenciesCNatural", testPitchSpellingFromTendenciesCNatural),
        ("testPitchSpellingFromTendenciesDDoubleFlat", testPitchSpellingFromTendenciesDDoubleFlat),
        ("testPitchSpellingFromTendenciesZeroNil", testPitchSpellingFromTendenciesZeroNil),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PitchSpellingCategoryTests.__allTests__PitchSpellingCategoryTests),
        testCase(TendencyTests.__allTests__TendencyTests),
    ]
}
#endif
