#if !canImport(ObjectiveC)
import XCTest

extension FlowNetworkTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FlowNetworkTests = [
        ("testEdges", testEdges),
        ("testMinimumCut", testMinimumCut),
        ("testPushFlow", testPushFlow),
        ("testPushFlowPath", testPushFlowPath),
        ("testRemoveEdges", testRemoveEdges),
        ("testResidualNetwork", testResidualNetwork),
    ]
}

extension FlowNodeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FlowNodeTests = [
        ("testBind", testBind),
        ("testDecodableFlowNode", testDecodableFlowNode),
        ("testEncodableFlowNode", testEncodableFlowNode),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FlowNetworkTests.__allTests__FlowNetworkTests),
        testCase(FlowNodeTests.__allTests__FlowNodeTests),
    ]
}
#endif
